src/main/default/objects/Trigger_Handler__mdt/fields/After_Delete__c.field-meta.xml
<CustomField>
    <fullName>After_Delete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>After Delete</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Trigger_Handler__mdt/fields/After_Insert__c.field-meta.xml
<CustomField>
    <fullName>After_Insert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>After Insert</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Trigger_Handler__mdt/fields/After_Undelete__c.field-meta.xml
<CustomField>
    <fullName>After_Undelete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>After Undelete</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Trigger_Handler__mdt/fields/After_Update__c.field-meta.xml
<CustomField>
    <fullName>After_Update__c</fullName>
    <defaultValue>false</defaultValue>
    <label>After Update</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Trigger_Handler__mdt/fields/Before_Delete__c.field-meta.xml
<CustomField>
    <fullName>Before_Delete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Before Delete</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Trigger_Handler__mdt/fields/Before_Insert__c.field-meta.xml
<CustomField>
    <fullName>Before_Insert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Before Insert</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Trigger_Handler__mdt/fields/Before_Update__c.field-meta.xml
<CustomField>
    <fullName>Before_Update__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Before Update</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Trigger_Handler__mdt/fields/Enabled__c.field-meta.xml
<CustomField>
    <fullName>Enabled__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If unchecked, this specific handler will be prevented from running. This also applies to legacy handler binding directly in master trigger.</description>
    <inlineHelpText>If unchecked, this specific handler will be prevented from running. This also applies to legacy handler binding directly in master trigger.</inlineHelpText>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Trigger_Handler__mdt/fields/Execution_Order__c.field-meta.xml
<CustomField>
    <fullName>Execution_Order__c</fullName>
    <description>Determines the order which the handlers will execute on a given object.</description>
    <inlineHelpText>Determines the order which the handlers will execute on a given object.</inlineHelpText>
    <label>Execution Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Trigger_Handler__mdt/fields/On_Exception__c.field-meta.xml
<CustomField>
    <fullName>On_Exception__c</fullName>
    <defaultValue>&quot;Throw&quot;</defaultValue>
    <description>Determines what happens in the event the trigger handler throws an exception:

Throw: The exception will be re-thrown
Suppress: The exception will only be logged (not recommended!)
Email: An email will be sent.  MUST ALSO SET Exception Email Recipients
CustomHandler: Name of class implementing &quot;CustomExeptionHandler&quot; to run on exception</description>
    <label>On Exception</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Throw</fullName>
                <default>true</default>
                <label>Throw</label>
            </value>
            <value>
                <fullName>Suppress</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Custom Handler</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Trigger_Handler__mdt/fields/On_Exception_Custom_Handler__c.field-meta.xml
<CustomField>
    <fullName>On_Exception_Custom_Handler__c</fullName>
    <description>CustomExceptionHandler class to run when an exception occurs.  &quot;On Exception&quot; must be set to &quot;Custom Handler&quot; for this to have an impact</description>
    <label>On Exception Custom Handler</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Trigger_Handler__mdt/fields/On_Exception_Email_Addresses__c.field-meta.xml
<CustomField>
    <fullName>On_Exception_Email_Addresses__c</fullName>
    <description>Comma separated list of email address to notify when an exception occurs</description>
    <inlineHelpText>Comma separated list of email address to notify when an exception occurs</inlineHelpText>
    <label>On Exception Email Addresses</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/classes/HandlerConfig.cls
/**
 * Class used to store all things related to a handler setup
 */
global class HandlerConfig {
    global enum ExceptionStrategy {
        RETHROW,
        SUPPRESS,
        EMAIL,
        CUSTOM
    }

    global Handler handler;

    global String className;
    global Boolean enabled;
    global Decimal order;
    global Boolean beforeInsert;
    global Boolean afterInsert;
    global Boolean beforeUpdate;
    global Boolean afterUpdate;
    global Boolean beforeDelete;
    global Boolean afterDelete;
    global Boolean afterUndelete;
    global ExceptionStrategy onException;
    global List<String> exceptionEmailRecipients;
    global String exceptionHandlerClassName;

    global HandlerConfig() {
    }

    /**
     * Constructor for missing config
     */
    global HandlerConfig(String className) {
        this.className = className;
        enabled = true;
        onException = ExceptionStrategy.RETHROW;
    }

    /**
     * Constructor used for dynamic bound handlers
     */
    global HandlerConfig(Trigger_Handler__mdt th) {
        className = th.Handler_Class__c.toLowerCase();
        enabled = th.Enabled__c;
        order = th.Execution_Order__c;
        beforeInsert = th.Before_Insert__c;
        afterInsert = th.After_Insert__c;
        beforeUpdate = th.Before_Update__c;
        afterUpdate = th.After_Update__c;
        beforeDelete = th.Before_Delete__c;
        afterDelete = th.After_Delete__c;
        afterUndelete = th.After_Undelete__c;
        onException = ExceptionStrategy.RETHROW;
        switch on th.On_Exception__c {
            when 'Suppress' {
                onException = ExceptionStrategy.SUPPRESS;
            }
            when 'Email' {
                if (!String.isEmpty(th.On_Exception_Email_Addresses__c)) {
                    onException = ExceptionStrategy.EMAIL;
                    exceptionEmailRecipients = th.On_Exception_Email_Addresses__c.split(',');
                }
            }
            when 'Custom Handler' {
                if (!String.isEmpty(th.On_Exception_Custom_Handler__c)) {
                    onException = ExceptionStrategy.CUSTOM;
                    exceptionHandlerClassName = th.On_Exception_Custom_Handler__c;
                } else {
                    System.debug('WARNING: "On_Exception__c" set to "Custom Handler" but handler was not specified.');
                }
            }
        }
    }
}