src/main/default/objects/Trigger_Handler_Exception__e/Trigger_Handler_Exception__e.object-meta.xml
<CustomObject>
    <description>Captures information about a trigger handler failing to run</description>
    <label>Trigger Handler Exception</label>
    <pluralLabel>Trigger Handler Exceptions</pluralLabel>
</CustomObject>

src/main/default/objects/Trigger_Handler_Exception__e/fields/Exception_Message__c.field-meta.xml
<CustomField>
    <fullName>Exception_Message__c</fullName>
    <description>The message of the thrown exception</description>
    <label>Exception Message</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/objects/Trigger_Handler_Exception__e/fields/Exception_Type__c.field-meta.xml
<CustomField>
    <fullName>Exception_Type__c</fullName>
    <description>The class type of the Exception logged</description>
    <label>Exception Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/objects/Trigger_Handler_Exception__e/fields/Handler_Config__c.field-meta.xml
<CustomField>
    <fullName>Handler_Config__c</fullName>
    <description>The current handler config</description>
    <label>Handler Config</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/objects/Trigger_Handler_Exception__e/fields/Handler_Config_Id__c.field-meta.xml
<CustomField>
    <fullName>Handler_Config_Id__c</fullName>
    <description>Used to retrieve additional information about handler config</description>
    <label>Handler Config Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Trigger_Handler_Exception__e/fields/New_Records__c.field-meta.xml
<CustomField>
    <fullName>New_Records__c</fullName>
    <label>New Records</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/objects/Trigger_Handler_Exception__e/fields/Old_Records__c.field-meta.xml
<CustomField>
    <fullName>Old_Records__c</fullName>
    <label>Old Records</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/objects/Trigger_Handler_Exception__e/fields/Size__c.field-meta.xml
<CustomField>
    <fullName>Size__c</fullName>
    <description>The number of records executing on</description>
    <label>Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Trigger_Handler_Exception__e/fields/SObject_Type__c.field-meta.xml
<CustomField>
    <fullName>SObject_Type__c</fullName>
    <description>The Type of the SObject the Trigger was running on</description>
    <label>SObject Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Trigger_Handler_Exception__e/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <description>The Stack trace of the thrown exception</description>
    <label>Stack Trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/objects/Trigger_Handler_Exception__e/fields/Trigger_Operation__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Operation__c</fullName>
    <description>The TriggerOperation Type</description>
    <label>Trigger Operation</label>
    <length>45</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Trigger_Handler_Exception__e/fields/User_Name__c.field-meta.xml
<CustomField>
    <fullName>User_Name__c</fullName>
    <description>The user the transaction was running as</description>
    <label>User Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/classes/TriggerExceptionTests.cls
/*
*  This class has to exist to cover the baked in exception management classes
*  SendEmailExceptionEventHandler, ExceptionEvent, and TriggerHandlerException
*/

@isTest
public with sharing class TriggerExceptionTests {
    @isTest
    public static void TriggerExceptionTests() {
        // we don't need to hit the database, just need to pass in what's needed for the test
        HandlerConfig hConfig = TriggerManageTests.generateHandlerTestData('TestHandler', true);
        Trigger_Handler_Exception__e thevt = new Trigger_Handler_Exception__e(
            User_Name__c = System.UserInfo.getUserName(),
            Exception_Type__c = 'textString',
            Exception_Message__c = 'textString',
            Stack_Trace__c = 'textString',
            Handler_Config_Id__c = 'textString',
            Handler_Config__c = JSON.serialize(hConfig),
            SObject_Type__c = 'Account',
            Trigger_Operation__c = 'Before_Insert',
            size__c = 1,
            New_Records__c = null,
            Old_Records__c = null
        );
        ExceptionEvent excEvt = new ExceptionEvent(thevt);
        // excEvt.config = hConfig;
        // excEvt.event =
        // excEvt.message = 'Test exception';
        // excEvt.operationType = System.TriggerOperation.BEFORE_INSERT;
        // excEvt.size = 1;
        // excEvt.SObjectType = 'Account';
        // excEvt.stackTrace = '--- test stack trace ---';
        // excEvt.type = 'test type';
        // excEvt.user = 'testuser';

        SendEmailExceptionEventHandler emailExEvHandler = new SendEmailExceptionEventHandler();
        emailExEvHandler.fromEmailAddress = 'test@example.com';
        emailExEvHandler.recipients = new String[]{'test@recip.com', 'test2@recip.com'};
        emailExEvHandler.handleExceptionEvents(excEvt);
    }
}