src/main/default/objects/Trigger_Handler_Exception__e/Trigger_Handler_Exception__e.object-meta.xml
<CustomObject>
    <description>Captures information about a trigger handler failing to run</description>
    <label>Trigger Handler Exception</label>
    <pluralLabel>Trigger Handler Exceptions</pluralLabel>
</CustomObject>

src/main/default/objects/Trigger_Handler_Exception__e/fields/Exception_Message__c.field-meta.xml
<CustomField>
    <fullName>Exception_Message__c</fullName>
    <description>The message of the thrown exception</description>
    <label>Exception Message</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/objects/Trigger_Handler_Exception__e/fields/Exception_Type__c.field-meta.xml
<CustomField>
    <fullName>Exception_Type__c</fullName>
    <description>The class type of the Exception logged</description>
    <label>Exception Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/objects/Trigger_Handler_Exception__e/fields/Handler_Config__c.field-meta.xml
<CustomField>
    <fullName>Handler_Config__c</fullName>
    <description>The current handler config</description>
    <label>Handler Config</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/objects/Trigger_Handler_Exception__e/fields/Size__c.field-meta.xml
<CustomField>
    <fullName>Size__c</fullName>
    <description>The number of records executing on</description>
    <label>Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Trigger_Handler_Exception__e/fields/SObject_Type__c.field-meta.xml
<CustomField>
    <fullName>SObject_Type__c</fullName>
    <description>The Type of the SObject the Trigger was running on</description>
    <label>SObject Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Trigger_Handler_Exception__e/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <description>The Stack trace of the thrown exception</description>
    <label>Stack Trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/objects/Trigger_Handler_Exception__e/fields/Trigger_Operation__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Operation__c</fullName>
    <description>The TriggerOperation Type</description>
    <label>Trigger Operation</label>
    <length>45</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Trigger_Handler_Exception__e/fields/User_Name__c.field-meta.xml
<CustomField>
    <fullName>User_Name__c</fullName>
    <description>The user the transaction was running as</description>
    <label>User Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/classes/ExceptionEvent.cls
/**
 * Abstraction of the  Trigger_Handler_Exception__e that is
 *   passed to `ExceptionEventHandler`
 */
global class ExceptionEvent {
    public String type;
    public String message;
    public String stackTrace;
    public String user;
    public HandlerConfig config;

    public TriggerOperation operationType;
    public Integer size;
    public String SObjectType;

    // useful for further serialization of records and what-not
    public Trigger_Handler_Exception__e event;

    public ExceptionEvent(Trigger_Handler_Exception__e e) {
        this.event = e;
        config = (HandlerConfig) JSON.deserialize(e.Handler_Config__c, HandlerConfig.class);

        // Exception Details
        type = e.Exception_Type__c;
        message = e.Exception_Message__c;
        stackTrace = e.Stack_Trace__c;

        // Context
        user = e.User_Name__c;
        sObjectType = e.SObject_Type__c;
        operationType = (TriggerOperation) Utils.parseEnum(e.Trigger_Operation__c, TriggerOperation.class);
        size = (Integer) e.Size__c;
    }
}